on:
  push:
    branches:
      - master
      - fix-actions-for-publishing

name: Publish to GitHub Package Registry on push to master
jobs:
  deployAllToGPR:
    name: Deploy all to GitHub Package Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GitHub Package Registry Login
      run: |
        echo "${{ secrets.GPR_PASSWORD }}" | docker login -u "${{ secrets.GPR_USERNAME }}" --password-stdin docker.pkg.github.com
    - name: Publish southwestcheckin to GitHub Package Registry
      uses: ./.github/actions/docker-make
      with:
        args: publish-southwestcheckin -e NAMESPACE=docker.pkg.github.com/parkr/dockerfiles
          -e TAG_PREFIX=sha-
    - name: Publish silence-but-for-error to GitHub Package Registry
      uses: ./.github/actions/docker-make
      with:
        args: publish-silence-but-for-error -e NAMESPACE=docker.pkg.github.com/parkr/dockerfiles
    - name: Publish rclone to GitHub Package Registry
      uses: ./.github/actions/docker-make
      with:
        args: publish-rclone -e NAMESPACE=docker.pkg.github.com/parkr/dockerfiles
    - name: Publish puppet-lint to GitHub Package Registry
      uses: ./.github/actions/docker-make
      with:
        args: publish-puppet-lint -e NAMESPACE=docker.pkg.github.com/parkr/dockerfiles
    - name: Publish octodns to GitHub Package Registry
      uses: ./.github/actions/docker-make
      with:
        args: publish-octodns -e NAMESPACE=docker.pkg.github.com/parkr/dockerfiles
    - name: Publish monicahq to GitHub Package Registry
      uses: ./.github/actions/docker-make
      with:
        args: publish-monicahq -e NAMESPACE=docker.pkg.github.com/parkr/dockerfiles
    - name: Publish git to GitHub Package Registry
      uses: ./.github/actions/docker-make
      with:
        args: publish-git -e NAMESPACE=docker.pkg.github.com/parkr/dockerfiles
    - name: Publish curl to GitHub Package Registry
      uses: ./.github/actions/docker-make
      with:
        args: publish-curl -e NAMESPACE=docker.pkg.github.com/parkr/dockerfiles
    - name: Publish checkup to GitHub Package Registry
      uses: ./.github/actions/docker-make
      with:
        args: publish-checkup -e NAMESPACE=docker.pkg.github.com/parkr/dockerfiles
          -e TAG_PREFIX=sha-
    - name: Publish aws-cli to GitHub Package Registry
      uses: ./.github/actions/docker-make
      with:
        args: publish-aws-cli -e NAMESPACE=docker.pkg.github.com/parkr/dockerfiles
          -e TAG_PREFIX=sha-
    - name: Publish airconnect to GitHub Package Registry
      uses: ./.github/actions/docker-make
      with:
        args: publish-airconnect -e NAMESPACE=docker.pkg.github.com/parkr/dockerfiles
          -e TAG_PREFIX=sha-
    - name: GitHub Package Registry Logout
      run: |
        docker logout docker.pkg.github.com
